version: '3'
services:
  cuda-llama.cpp:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: ./server-mm -m examples/llava/phi3-models/gguf/ggml-model-f16.gguf --mmproj examples/llava/phi3-models/gguf/vit/mmproj-model-f16.gguf -c 4096 --host 0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # use all GPUs or the specified ones:
            # device_ids: ['0','1','2','3']
            capabilities: [gpu]
