version: '3'
services:
  cuda-llama.cpp:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    volumes:
      - .:/app
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # use all GPUs or the specified ones:
            # device_ids: ['0','1','2','3']
            capabilities: [gpu]
